name = "micr-api"
main = "worker/index.js"
compatibility_date = "2024-01-01"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "micr-db"
database_id = "8cbc8c02-98ca-4eca-9226-2ab098938885" # Will be filled after creating the database

# Environment variables
[vars]
ENVIRONMENT = "production"

# Scheduled tasks (Cron)
[triggers]
crons = ["0 0 * * 1"] # Раз в неделю (понедельник, 00:00)

# Development environment
[env.dev]
name = "micr-api-dev"
vars = { ENVIRONMENT = "development" }

# Routes for custom domain
routes = [
  { pattern = "api.micr.fun/*", zone_name = "micr.fun" }
]
